Web Flow With External Server Posting Back/force-app/main/objects/MDAPIClientSettings__c/MDAPIClientSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Reserved for future use.</description>
    <label>Metadata API Client Settings</label>
</CustomObject>

Web Flow With External Server Posting Back/force-app/main/objects/MDAPIClientSettings__c/fields/AllowRefreshTokens__c.field-meta.xml
<CustomField>
    <fullName>AllowRefreshTokens__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Allow Refresh Tokens</label>
    <type>Checkbox</type>
</CustomField>

Web Flow With External Server Posting Back/force-app/main/objects/MDAPIClientSettings__c/fields/UseLargeTokenStore__c.field-meta.xml
<CustomField>
    <fullName>UseLargeTokenStore__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SObject Based Token Store for Web Flow</label>
    <type>Checkbox</type>
</CustomField>

Web Flow With External Server Posting Back/force-app/main/classes/selectors/MdApiSettingsSelectorTest.cls
@IsTest
public inherited sharing class MdApiSettingsSelectorTest
{
    @IsTest
    public static void givenNoSavedSettings_ICanGetCorrectDefaults() {
        MDAPIClientSettings__c settings = MdApiSettingsSelector.getSettings();
        System.assertEquals(true, settings.AllowRefreshTokens__c);
    }

        @IsTest
    public static void givenSavedSettings_ICanGetCorrectValues() {

        MDAPIClientSettings__c newInstance = new MDAPIClientSettings__c(
            AllowRefreshTokens__c = false
        );
        insert newInstance;

        Test.startTest();
        MDAPIClientSettings__c settings = MdApiSettingsSelector.getSettings();      
        System.assertEquals(false, settings.AllowRefreshTokens__c);
        Test.stopTest();
    }

    @IsTest
    public static void ifAPartialSettingsHasBeenSaved_defaultsArePreserved() {

        MDAPIClientSettings__c newInstance = new MDAPIClientSettings__c(
            UseLargeTokenStore__c = true
        );
        insert newInstance;

        Test.startTest();
        MDAPIClientSettings__c settings = MdApiSettingsSelector.getSettings();      
        System.assertEquals(true, settings.AllowRefreshTokens__c);
        Test.stopTest();
    }

}